### ISSUE TITLE
"TODO: perhaps if not set then all layers on the map are selectable?"

### ISSUE THREAD

**Issue by Pointotech** [Leaflet/Leaflet.draw#990]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leaflet.github.io/Leaflet.draw/dist/reference-0.4.1.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet Draw code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.6.0
- Leaflet Draw version I'm using: 1.0.3
- Browser (with version) I'm using: Firefox 75.0 (32-bit)
- OS/Platform (with version) I'm using: Windows 10 Pro 1903 build 18362.778
- This is not a runtime issue. It is a code quality issue.

## What behaviour I'm expecting and which behaviour I'm seeing

In `EditToobar.js`, on line 28: https://github.com/Leaflet/Leaflet.draw/blob/d5dd11781c2e07f9e719308e504fe579000edf54/src/edit/EditToolbar.js#L28

The comment says: `REQUIRED! TODO: perhaps if not set then all layers on the map are selectable?`

Do we know if this is still something to be done? If this is a bug, or an edge case that needs to be handled, or a new feature that's being developed, can someone describe it?

If it's no longer relevant, can we remove it?

I'll gladly raise a pull request to address this either way, if I have requirements.

Thank you :)

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

https://github.com/Leaflet/Leaflet.draw/blob/d5dd11781c2e07f9e719308e504fe579000edf54/src/edit/EditToolbar.js#L28

I found one more TODO comment which has a similar issue:

- https://github.com/Leaflet/Leaflet.draw/blob/d5dd11781c2e07f9e719308e504fe579000edf54/src/Toolbar.js#L267
